server:
  port: 8090

spring:

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/master
          jwk-set-uri: http://localhost:8080/auth/realms/master/protocol/openid-connect/certs

  liquibase:
    change-log: classpath:db/changelog/master.xml

  datasource:
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vtbhack

#  security:
#    jwt:
#      secret: df2f62jKf2iuvbVwu1c7xn4djkbVVndd
#      expires: 864000 # 10 * 24 * 60 * 60

headers:
  allow-origin: '*'
  max-age: 3600

