server:
  port: 80

spring:

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST}/auth/realms/${KEYCLOAK_REALM}
          jwk-set-uri: http://${KEYCLOAK_HOST}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs

  datasource:
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    host: ${PG_HOST}
    datebase: ${PG_DATABASE}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${spring.datasource.host}/${spring.datasource.datebase}


