server:
  port: 80

spring:

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.host}/auth/realms/${keycloak.realm}
          jwk-set-uri: ${keycloak.host}/auth/realms/${keycloak.realm}/protocol/openid-connect/certs

  datasource:
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    host: ${PG_HOST}
    datebase: ${PG_DATABASE}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${spring.datasource.host}/${spring.datasource.datebase}

keycloak:
  host: ${KEYCLOAK_HOST}
  realm: ${KEYCLOAK_REALM}
  client-id: ${KEYCLOAK_CLIENT}
